---
log:
  level: debug
accessLog:
  filePath: /var/log/traefik/access.log

api:
  insecure: false
  dashboard: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs: {{CLOUDFLARE_TRUSTED_IPS}}

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    swarmMode: true

certificatesresolvers:
  cloudflare:
    acme:
      dnschallenge:
        provider: cloudflare
      storage: /letsencrypt/acme.json
